version: '3.8'

services:
  server:
    container_name: server-container
    build: ./server
    env_file: 
      - ./server/.env 
    ports:
      - "4000:4000"    
    networks:
      - folioapp
    restart: unless-stopped 


  frontend:
    container_name: client-container
    build: ./frontend
    env_file:
      - ./frontend/.env  
    ports:
      - "3000:3000"     
    networks:
      - folioapp
    depends_on:
      - server         
    restart: unless-stopped

networks:
  folioapp:
    driver: bridge